[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[project]
name = "pygments-vscode-onedark"
version = "0.1.0"
dependencies = ["pygments>=2.10"]

[project.entry-points."pygments.styles"]
vscode_onedark = "vscode_onedark:VscodeOneDarkStyle"
